services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    env_file:
      - .env
    volumes:
      - ./alembic:/app/alembic
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    networks:
      - app_network
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.spravki-back.rule=Host(`sesc-it-team.ru`) && PathPrefix(`/spravki-back`)
      - traefik.http.routers.spravki-back.entrypoints=web
      - traefik.http.routers.spravki-back.middlewares=spravki-back-strip
      - traefik.http.routers.spravki-back-secure.rule=Host(`sesc-it-team.ru`) && PathPrefix(`/spravki-back`)
      - traefik.http.routers.spravki-back-secure.entrypoints=websecure
      - traefik.http.routers.spravki-back-secure.tls=true
      - traefik.http.routers.spravki-back-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.spravki-back-secure.middlewares=spravki-back-strip
      - traefik.http.middlewares.spravki-back-strip.stripprefix.prefixes=/spravki-back
      - traefik.http.services.spravki-back.loadbalancer.server.port=8000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .idea/
        - action: rebuild
          path: ./uv.lock

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
  traefik-public:
    external: true
    name: traefik-public