services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./alembic:/app/alembic
    depends_on:
      postgres:
        condition: service_started
    command: sh entrypoint.sh
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: certificates
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
