"""add department column

Revision ID: 437bc321a964
Revises: 6a4177c6cd70
Create Date: 2026-03-20 14:00:44.973529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '437bc321a964'
down_revision: Union[str, Sequence[str], None] = '6a4177c6cd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_actions', sa.Column('department', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_actions', 'department')
    # ### end Alembic commands ###
