"""comment

Revision ID: 7ef2c7204b66
Revises: b57b383b8bea
Create Date: 2026-06-21 21:38:47.579660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef2c7204b66'
down_revision: Union[str, Sequence[str], None] = 'b57b383b8bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_actions', sa.Column('user_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_actions', 'user_id')
    # ### end Alembic commands ###
