"""MISHA NAYCHISb PISATb BACKEND

Revision ID: a0d2a694d676
Revises: 7ef2c7204b66BACKEND.983712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d2a694d676'
down_revision: Union[str, Sequence[str], None] = '7ef2c7204b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_actions', sa.Column('child_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_actions', 'child_id')
    # ### end Alembic commands ###
