"""sth

Revision ID: b57b383b8bea
Revises: c63f51925372
Create Date: 2026-05-14 23:11:08.760054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57b383b8bea'
down_revision: Union[str, Sequence[str], None] = 'c63f51925372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_certificate_actions_id'), 'certificate_actions', ['id'], unique=False)
    # 1. Create the new sequence
    op.execute("CREATE SEQUENCE document_number_seq")

    # 2. Set the sequence start value to max existing value + 1
    op.execute("SELECT setval('document_number_seq', COALESCE((SELECT MAX(number) FROM certificate_actions), 1))")

    # 3. Change column default to use the sequence
    op.alter_column('certificate_actions', 'number',
                    server_default=sa.text("nextval('document_number_seq')"))

    # 4. If the column had SERIAL, remove the implicit sequence ownership
    # (PostgreSQL might have created an implicit sequence like table_name_column_name_seq)
    op.execute("ALTER SEQUENCE IF EXISTS document_number_seq OWNED BY certificate_actions.number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_actions_id'), table_name='certificate_actions')

    op.alter_column('certificate_actions', 'number',
                    server_default=sa.text("nextval('document_number_seq'::regclass)"))
    # Or just set to autoincrement
    # op.execute("ALTER TABLE certificate_actions ALTER COLUMN number SET DEFAULT nextval('document_number_seq')")
    # ### end Alembic commands ###
