"""something

Revision ID: c63f51925372
Revises: 437bc321a964
Create Date: 2026-05-14 22:21:17.436153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c63f51925372'
down_revision: Union[str, Sequence[str], None] = '437bc321a964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку number с временным значением по умолчанию
    # Сначала добавляем как NULL
    op.add_column('certificate_actions', sa.Column('number', sa.Integer(), nullable=True))

    # Заполняем существующие строки (например, порядковыми номерами)
    op.execute("""
        UPDATE certificate_actions 
        SET number = subquery.row_num 
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY id) as row_num 
            FROM certificate_actions
        ) AS subquery 
        WHERE certificate_actions.id = subquery.id
    """)

    # Теперь делаем NOT NULL
    op.alter_column('certificate_actions', 'number', nullable=False)

    # Создаем SEQUENCE для автоинкремента
    op.execute("CREATE SEQUENCE IF NOT EXISTS certificate_actions_number_seq")
    op.execute(
        "ALTER TABLE certificate_actions ALTER COLUMN number SET DEFAULT nextval('certificate_actions_number_seq')")

    # 2. Добавляем колонку link
    op.add_column('certificate_actions', sa.Column('link', sa.String(), nullable=True))

    # 3. Временная колонка для UUID
    op.add_column('certificate_actions', sa.Column('_id_uuid', sa.Uuid(), nullable=True))

    # 4. Заполняем новыми UUID
    op.execute("UPDATE certificate_actions SET _id_uuid = gen_random_uuid()")

    # 5. Делаем NOT NULL
    op.alter_column('certificate_actions', '_id_uuid', nullable=False)

    # 6. Убираем старый PK
    op.drop_constraint('certificate_actions_pkey', 'certificate_actions', type_='primary')

    # 7. Удаляем старую колонку id
    op.drop_column('certificate_actions', 'id')

    # 8. Переименовываем новую
    op.alter_column('certificate_actions', '_id_uuid', new_column_name='id')

    # 9. Восстанавливаем PK
    op.create_primary_key('certificate_actions_pkey', 'certificate_actions', ['id'])

    # 10. Остальные изменения
    op.alter_column('certificate_actions', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('certificate_actions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('certificate_actions', 'link')
    op.drop_column('certificate_actions', 'number')
    # ### end Alembic commands ###
