"""something

Revision ID: c63f51925372
Revises: 437bc321a964
Create Date: 2026-05-14 22:21:17.436153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c63f51925372'
down_revision: Union[str, Sequence[str], None] = '437bc321a964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем новые колонки (как у тебя)
    op.add_column('certificate_actions', sa.Column('number', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('certificate_actions', sa.Column('link', sa.String(), nullable=True))

    # 2. Временная колонка для UUID
    op.add_column('certificate_actions', sa.Column('_id_uuid', sa.Uuid(), nullable=True))

    # 3. Заполняем новыми UUID
    op.execute("UPDATE certificate_actions SET _id_uuid = gen_random_uuid()")

    # 4. Делаем NOT NULL
    op.alter_column('certificate_actions', '_id_uuid', nullable=False)

    # 5. Убираем старый PK
    op.drop_constraint('certificate_actions_pkey', 'certificate_actions', type_='primary')

    # 6. Удаляем старую колонку id
    op.drop_column('certificate_actions', 'id')

    # 7. Переименовываем новую
    op.alter_column('certificate_actions', '_id_uuid', new_column_name='id')

    # 8. Восстанавливаем PK
    op.create_primary_key('certificate_actions_pkey', 'certificate_actions', ['id'])

    # 9. Остальные изменения
    op.alter_column('certificate_actions', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False,
                    existing_server_default=sa.text('now()'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certificate_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('certificate_actions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('certificate_actions', 'link')
    op.drop_column('certificate_actions', 'number')
    # ### end Alembic commands ###
